//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoVendoRecargaAPI.SVC.WebServiceClaro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://principal.claro.com/", ConfigurationName="WebServiceClaro.ActivarPin")]
    public interface ActivarPin {
        
        // CODEGEN: Generating message contract since element name telefono from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://principal.claro.com/ActivarPin/activarPinPromocionalRequest", ReplyAction="http://principal.claro.com/ActivarPin/activarPinPromocionalResponse")]
        YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalResponse activarPinPromocional(YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://principal.claro.com/ActivarPin/activarPinPromocionalRequest", ReplyAction="http://principal.claro.com/ActivarPin/activarPinPromocionalResponse")]
        System.Threading.Tasks.Task<YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalResponse> activarPinPromocionalAsync(YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class activarPinPromocionalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="activarPinPromocional", Namespace="http://principal.claro.com/", Order=0)]
        public YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalRequestBody Body;
        
        public activarPinPromocionalRequest() {
        }
        
        public activarPinPromocionalRequest(YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class activarPinPromocionalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string procedencia;
        
        public activarPinPromocionalRequestBody() {
        }
        
        public activarPinPromocionalRequestBody(string telefono, string pin, string procedencia) {
            this.telefono = telefono;
            this.pin = pin;
            this.procedencia = procedencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class activarPinPromocionalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="activarPinPromocionalResponse", Namespace="http://principal.claro.com/", Order=0)]
        public YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalResponseBody Body;
        
        public activarPinPromocionalResponse() {
        }
        
        public activarPinPromocionalResponse(YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class activarPinPromocionalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public activarPinPromocionalResponseBody() {
        }
        
        public activarPinPromocionalResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActivarPinChannel : YoVendoRecargaAPI.SVC.WebServiceClaro.ActivarPin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActivarPinClient : System.ServiceModel.ClientBase<YoVendoRecargaAPI.SVC.WebServiceClaro.ActivarPin>, YoVendoRecargaAPI.SVC.WebServiceClaro.ActivarPin {
        
        public ActivarPinClient() {
        }
        
        public ActivarPinClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActivarPinClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivarPinClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivarPinClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalResponse YoVendoRecargaAPI.SVC.WebServiceClaro.ActivarPin.activarPinPromocional(YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalRequest request) {
            return base.Channel.activarPinPromocional(request);
        }
        
        public string activarPinPromocional(string telefono, string pin, string procedencia) {
            YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalRequest inValue = new YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalRequest();
            inValue.Body = new YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalRequestBody();
            inValue.Body.telefono = telefono;
            inValue.Body.pin = pin;
            inValue.Body.procedencia = procedencia;
            YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalResponse retVal = ((YoVendoRecargaAPI.SVC.WebServiceClaro.ActivarPin)(this)).activarPinPromocional(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalResponse> YoVendoRecargaAPI.SVC.WebServiceClaro.ActivarPin.activarPinPromocionalAsync(YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalRequest request) {
            return base.Channel.activarPinPromocionalAsync(request);
        }
        
        public System.Threading.Tasks.Task<YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalResponse> activarPinPromocionalAsync(string telefono, string pin, string procedencia) {
            YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalRequest inValue = new YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalRequest();
            inValue.Body = new YoVendoRecargaAPI.SVC.WebServiceClaro.activarPinPromocionalRequestBody();
            inValue.Body.telefono = telefono;
            inValue.Body.pin = pin;
            inValue.Body.procedencia = procedencia;
            return ((YoVendoRecargaAPI.SVC.WebServiceClaro.ActivarPin)(this)).activarPinPromocionalAsync(inValue);
        }
    }
}
